import { Poppins } from 'next/font/google'
import "./globals.css";
import TTSFocusReader from './components/TTSFocusReader';
import FullScreenDetector from './components/FullScreenDetector';

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const poppins = Poppins({
    subsets: ['latin'],
    display: 'swap',
    weight: ['100', '200', '400', '500', '600', '700', '800', '900'],
})

export default function RootLayout({ children }) {
    return (
        <html lang="nl-NL">
            <body className={poppins.className}>
                <TTSFocusReader />
                <FullScreenDetector />
                {children}
            </body>
        </html>
    );
}